export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_SUCCEEDED = 'API_REQUEST_SUCCEEDED';
export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';
export const API_LOGIN_REQUEST = 'LOGIN_REQUEST';
export const API_LOGIN_REQUEST_SUCCEEDED = 'LOGIN_REQUEST_SUCCCEEDED';
export const API_LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';
export const LOCATION_CHANGED = 'LOCATION_CHANGED';
export const LOCATION_CHANGED_SUCCESS = 'LOCATION_CHANGED_SUCCEEDED';
export const LOCATION_CHANGED_FAILED = 'LOCATION_CHANGED_FAILED';
export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const FACEBOOK_LOGIN_SUCCEED = 'FACEBOOK_LOGIN_SUCCEED';
export const FACEBOOK_LOGIN_FAILED = 'FACEBOOK_LOGIN_FAILED';
export const LOAD_TOKEN_FROM_STORAGE = 'LOAD_TOKEN_FROM_STORAGE';
export const LOAD_TOKEN_FROM_STORAGE_SUCCEEDED = 'LOAD_TOKEN_FROM_STORAGE_SUCCEEDED';
export const LOAD_TOKEN_FROM_STORAGE_FAILED = 'LOAD_TOKEN_FROM_STORAGE_FAILED';

export const GET_SERVICES_API = 'GET_SERVICES_API';
export const GET_SERVICES_API_SUCCEED = 'GET_SERVICES_API_SUCCEED';
export const GET_SERVICES_API_FAILED = 'GET_SERVICES_API_FAILED';

export const GET_PLACED_ORDER_API = 'GET_PLACED_ORDER_API';
export const GET_PLACED_ORDER_SUCCEED = 'GET_PLACED_ORDER_SUCCEED';
export const GET_PLACED_ORDER_FAILED = 'GET_PLACED_ORDER_FAILED';

export const GET_NOTIFICATIONS_API = 'GET_NOTIFICATIONS_API';
export const GET_NOTIFICATIONS_SUCCEED = 'GET_NOTIFICATIONS_SUCCEED';
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED';

export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';
export const CREATE_NEW_ORDER_SUCCEED = 'CREATE_NEW_ORDER_SUCCEED';
export const CREATE_NEW_ORDER_FAILED = 'CREATE_NEW_ORDER_FAILED';

